services:
  postgres-db:
    image: postgres:18.6-alpine
    container_name: web-portfolio-database
    restart: always
    env_file:
      - './backend/.env.test'
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql

  backend:
    build:
      dockerfile: ./backend/Dockerfile
    container_name: web-portfolio-backend
    restart: always
    depends_on:
      - postgres-db
    ports:
      - "8080:8080"
    env_file:
      - './backend/.env.test'

volumes:
  pg-data: