[versions]
lombok = "1.18.46"
spring-boot = "4.0.6"
spring-dependency-management = "1.1.7"
mapstruct = "1.6.3"
uuid-creator-ver = "6.1.1"

[libraries]
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
mapstruct = { group = "org.mapstruct", name = "mapstruct", version.ref = "mapstruct" }
mapstruct-processor = { group = "org.mapstruct", name = "mapstruct-processor", version.ref = "mapstruct" }
uuid-creator = { group = "com.github.f4b6a3", name = "uuid-creator", version.ref = "uuid-creator-ver"}

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }