name: "Setup Backend Environment"
description: "Installs JDK 21 and Gradle"

runs:
  using: "composite"
  steps:
    - name: Set up JDK 21
      uses: actions/setup-java@v5.7.0
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v6