spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  mvc:
    problemdetails:
      enabled: true
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:mydb}
    username: ${DATABASE_USER:myuser}
    password: ${DATABASE_PASSWORD:mypassword}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    parameters:
      admin-username: ${ADMIN_USERNAME:test}
      admin-password-hash: ${ADMIN_PASSWORD_HASH:$2a$15$3dSezSi7qDOo7QLI9AscnegxdD.N.ResBGtWq0ve4nlZc.yaanxDy}

springdoc:
  swagger-ui:
    enabled: true

  api-docs:
    enabled: true
