name: Reusable Build
on:
  workflow_call:
    inputs:
      project_type:
        required: true
        type: string
      branch_name:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          TAG=${{ inputs.branch_name == 'main' && 'main' || 'test' }}
          echo "Building $PROJECT_TYPE as $TAG..."