name: Reusable Deploy
on:
  workflow_call:
    inputs:
      branch_name:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            
            PROJECT_DIR="$HOME/web-portfolio"
            
            if [ ! -d "$PROJECT_DIR" ]; then
              echo "Project directory not found. Cloning..."
              git clone git@github.com:${{ github.repository }}.git $PROJECT_DIR
            fi
            
            cd $PROJECT_DIR
            
            echo "Updating code to branch ${{ github.ref_name }}..."
            git fetch origin
            git checkout ${{ github.ref_name }}
            git pull origin ${{ github.ref_name }}
            
            if [ "${{ github.ref_name }}" == "main" ]; then
              SERVICE="portfolio-prod"
            else
              SERVICE="portfolio-test"
            fi
            
            echo "Deploying $SERVICE..."
            docker compose up -d --build $SERVICE
            docker image prune -f